server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:employee_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

app:
  identifier: Employee Manager
